### ISSUE TITLE
bug: Use medatata credentials in credentials_from_env_variables by default

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb-python-sdk#269]
# Bug Report

now if credentials_from_env_variables called and no env variables - used anonymous auth instead of metadata.

**Comment by max-arnold** [comment]
Since I was asked in the Telegram chat to file an issue, I'm posting my findings here.

The [docs](https://ydb.tech/en/docs/reference/ydb-sdk/auth) and the code seem to diverge:

1. SDK 2.x [does use](https://github.com/ydb-platform/ydb-python-sdk/blob/2.13.3/ydb/driver.py#L23-L56) metadata credentials by default, but the Python SDK note in the docs says otherwise `Or else, no authentication information is added to requests`
2. SDK 3.x [doesn't use it](https://github.com/ydb-platform/ydb-python-sdk/blob/3.2.0/ydb/driver.py#L19-L57) (anonymous auth is the default one). This breaks serverless functions even if you use `credentials_from_env_variables` mentioned in the changelog. I had to add both `credentials_from_env_variables` and export `YDB_METADATA_CREDENTIALS=1` to get the 2.x behavior back. I believe this is a regression, or a breaking change.
3. The docs mention the `SA_KEY_FILE` env var, but it is only used in [the example](https://github.com/ydb-platform/ydb-python-sdk/blob/main/examples/service-account-credentials/main.py). SDK code uses `YDB_SERVICE_ACCOUNT_KEY_FILE_CREDENTIALS`
4. Examples like [this one](https://github.com/ydb-platform/ydb-python-sdk/blob/main/examples/cloud-function-trivial-example/index.py) do not work and should be updated to use `credentials_from_env_variables` and `YDB_METADATA_CREDENTIALS=1`.

My use-case:

```python
        self.driver = ydb.Driver(
            endpoint=endpoint or os.getenv("YDB_ENDPOINT"),
            database=database or os.getenv("YDB_DATABASE"),
        )
```

This code worked with SDK 2.x both on a local machine (with `YDB_SERVICE_ACCOUNT_KEY_FILE_CREDENTIALS`, `YDB_ENDPOINT`, and `YDB_DATABASE` defined) and in a serverless function context (with `YDB_ENDPOINT` and `YDB_DATABASE` defined).

Upgrading to SDK 3.x broke the code in both environments (local/serverless). Changing it as per the changelog, fixed the local runs, but not serverless:

```python
        self.driver = ydb.Driver(
            endpoint=endpoint or os.getenv("YDB_ENDPOINT"),
            database=database or os.getenv("YDB_DATABASE"),
            credentials=ydb.credentials_from_env_variables()
        )
```

To really fix it I had to add `YDB_METADATA_CREDENTIALS=1` to each serverless function environment.
